services:
  database:
    image: mysql/mysql-server:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=payment_reminder
      - TZ=America/Los_Angeles
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 512M
    command:
      - --bind-address=0.0.0.0
      - --performance_schema=OFF
      - --table_definition_cache=200
      - --table_open_cache=128
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --net_read_timeout=30
      - --net_write_timeout=60
      - --connect_timeout=10

networks:
  app-network:
    driver: bridge

volumes:
  my-db:
