version: '3.9'

services:
  backend:
    image: elliotpark410/payment_reminder_server:latest
    container_name: backend
    env_file: ../.env
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    networks:
      - app-network
    restart: unless-stopped
    platform: linux/amd64

  database:
    image: mysql/mysql-server:8.0
    container_name: mysql
    env_file: ../.env
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redis
    env_file: ../.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  my-db:
