version: '3.9'

services:
  frontend:
    image: elliotpark410/payment_reminder_react
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  # backend:
  #   image: elliotpark410/payment_reminder_server
  #   container_name: backend
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_HOST=database
  #     - DATABASE_NAME=${MYSQL_DATABASE}
  #     - DATABASE_USER=${MYSQL_USER}
  #     - DATABASE_PASSWORD=${MYSQL_PASSWORD}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network
  #   ports:
  #     - "3000:3000"

  # database:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #   env_file:
  #     - .env
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - app-network
  #   restart: unless-stopped

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
