version: '3.9'

services:
  database:
    image: mysql/mysql-server:8.0
    container_name: mysql
    env_file: ../.env
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redis
    env_file: ../.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  my-db:
