version: '3.9'

services:
  database:
    image: mysql/mysql-server:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=payment_reminder
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    command:
      - --performance_schema=OFF
      - --table_definition_cache=200
      - --table_open_cache=128

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru

networks:
  app-network:
    driver: bridge

volumes:
  my-db:
